version: "3.4"
services:
  backend:
    image: multiagent-api:1.0
    build: ./autogen-copilot
    ports:
      - "5000:5000"
    environment:
      - USE_SQLLITE=True

  frontend:
    image: chat-fluentui:1.0
    build: ./chat-fluentui
    ports:
      - "3000:3000"
    depends_on:
      - backend
